apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: rigup
  labels:
    app: rigup
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      namespace: rigup
      labels:
        app: rigup
        type: frontend
    spec: 
      containers:
        - name: frontend-server
          image: tiff19/frontend-rigup:tagVersion
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: rigup
  labels:
    app: rigup
    type: frontend
spec:
  type: LoadBalancer
  selector:
    type: frontend
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30013
